# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!
  FLAKE_DIR: ./nix/.config/nix
  FLAKE_CONFIG: gawrgare-home

tasks:
  rebuild-nix:
    cmds:
      - sudo darwin-rebuild switch --flake {{ .FLAKE_DIR }}#{{ .FLAKE_CONFIG }}
  install-nix:
    cmds:
      - sudo nix run nix-darwin/master#darwin-rebuild -- switch --flake {{ .FLAKE_DIR }}#{{ .FLAKE_CONFIG }}
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
