set -e fish_user_paths

# Homebrew generated by `brew shellenv`
set -gx HOMEBREW_PREFIX /opt/homebrew
set -gx HOMEBREW_CELLAR /opt/homebrew/Cellar
set -gx HOMEBREW_REPOSITORY /opt/homebrew
set -q PATH; or set PATH ''
set -gx PATH /opt/homebrew/bin /opt/homebrew/sbin $PATH
set -q MANPATH; or set MANPATH ''
set -gx MANPATH /opt/homebrew/share/man $MANPATH
set -q INFOPATH; or set INFOPATH ''
set -gx INFOPATH /opt/homebrew/share/info $INFOPATH
set -gx PATH $PATH $HOME/.krew/bin

set -x ZSH "$HOME/.oh-my-zsh"
set -x PATH "~/Library/Python/3.9/bin:$PATH"
set -x PATH "$PATH:/usr/bin"
set -x PATH "$HOME/.tmuxifier/bin:$PATH"
set -x PATH "/opt/homebrew/opt/ruby/bin:$PATH"

# Go
set -x GOPATH "$HOME/go"
set -x GOROOT "$(brew --prefix golang)/libexec"
set -x PATH "$PATH:$GOPATH/bin"
set -x PATH "$PATH:$GOROOT/bin"

# tmuxifier
set -x TMUXIFIER_NO_COMPLETE 1
set -x EDITOR nvim

# FZF
set -Ux FZF_DEFAULT_COMMAND "fd --type f"
set -Ux FZF_CTRL_T_COMMAND "fd --type f"
set -Ux FZF_ALT_C_COMMAND "fd --type d"
