set -e fish_user_paths

# mise shims must come before system paths so mise-managed tools (e.g. ruby)
# take priority over macOS system versions in /usr/bin
set -gx PATH $HOME/.local/share/mise/shims $PATH

# Homebrew generated by `brew shellenv`
set -gx HOMEBREW_PREFIX /opt/homebrew
set -gx HOMEBREW_CELLAR /opt/homebrew/Cellar
set -gx HOMEBREW_REPOSITORY /opt/homebrew
set -q PATH; or set PATH ''
set -gx PATH /opt/homebrew/bin /opt/homebrew/sbin $PATH
set -q MANPATH; or set MANPATH ''
set -gx MANPATH /opt/homebrew/share/man $MANPATH
set -q INFOPATH; or set INFOPATH ''
set -gx INFOPATH /opt/homebrew/share/info $INFOPATH
set -gx PATH $PATH $HOME/.krew/bin
set -gx PATH /nix/var/nix/profiles/default/bin $PATH
set -gx PATH /run/current-system/sw/bin $PATH

set -x ZSH "$HOME/.oh-my-zsh"
fish_add_path $HOME/.tmuxifier/bin
# set -x PATH "/opt/homebrew/opt/ruby/bin:$PATH"

# Go
# set -x GOPATH "$HOME/go"
# set -x GOROOT "$(brew --prefix golang)/libexec"
# set -x PATH "$PATH:$GOPATH/bin"
# set -x PATH "$PATH:$GOROOT/bin"

# tmuxifier
set -x TMUXIFIER_NO_COMPLETE 1
set -x EDITOR nvim

# FZF
set -Ux FZF_DEFAULT_COMMAND "fd --type f"
set -Ux FZF_CTRL_T_COMMAND "fd --type f"
set -Ux FZF_ALT_C_COMMAND "fd --type d"
